targets:
  - job_name: 'grafana'
    host: grafana-central
    port: 3000
  - job_name: 'blackbox'
    host: blackbox-exporter
    port: 9115
  - job_name: 'snmp'
    host: snmp-exporter
    port: 9116
  - job_name: 'snmp'
    host: snmp-exporter
    port: 9116
  - job_name: 'node-exporter'
    host: node-exporter
    port: 9100
